#!/usr/bin/env node
/*
  build-sitemap.js — writes sitemap.xml for the public pages.

  lastmod comes from each file's last git commit date, so the sitemap only
  claims a page changed when it did. mobile.html is left out on purpose: it
  is a generated copy of index.html and carries a canonical link back to it.
  copydesk.html, 404.html and everything under content/, docs/ and scripts/
  are noindex or blocked in robots.txt.

  Usage:
    node scripts/build-sitemap.js          # write sitemap.xml
    node scripts/build-sitemap.js --check  # exit 1 if sitemap.xml is stale
*/

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const TARGET = path.join(ROOT, 'sitemap.xml');
const ORIGIN = 'https://www.htg.productions/';

/* [file, url path, priority, changefreq] — order is the order in the file. */
const PAGES = [
  ['index.html', '', '1.0', 'weekly'],
  ['abraxas.html', 'abraxas.html', '0.9', 'monthly'],
  ['stretty.html', 'stretty.html', '0.9', 'monthly'],
  ['ciggie.html', 'ciggie.html', '0.8', 'monthly'],
  ['justin.html', 'justin.html', '0.8', 'monthly'],
  ['sequence.html', 'sequence.html', '0.8', 'monthly'],
  ['game.html', 'game.html', '0.7', 'monthly'],
  ['rain.html', 'rain.html', '0.6', 'monthly'],
  ['roster.html', 'roster.html', '0.8', 'monthly'],
  ['music.html', 'music.html', '0.8', 'monthly'],
  ['gallery.html', 'gallery.html', '0.6', 'monthly'],
  ['contact.html', 'contact.html', '0.6', 'monthly'],
  ['legal.html', 'legal.html', '0.3', 'yearly'],
];

function lastmod(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(out)) return out;
  } catch (e) {
    /* not a git checkout — fall through */
  }
  return new Date().toISOString().slice(0, 10);
}

function build() {
  const rows = PAGES.map(([file, slug, priority, changefreq]) => {
    if (!fs.existsSync(path.join(ROOT, file))) {
      throw new Error(`build-sitemap: ${file} is listed but does not exist`);
    }
    return (
      '  <url>\n' +
      `    <loc>${ORIGIN}${slug}</loc>\n` +
      `    <lastmod>${lastmod(file)}</lastmod>\n` +
      `    <changefreq>${changefreq}</changefreq>\n` +
      `    <priority>${priority}</priority>\n` +
      '  </url>\n'
    );
  });
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!-- Generated by scripts/build-sitemap.js. Run `npm run build:sitemap`\n' +
    '     after editing a page; lastmod is the page\'s last commit date. -->\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    rows.join('') +
    '</urlset>\n'
  );
}

function main() {
  const xml = build();
  if (!process.argv.includes('--check')) {
    fs.writeFileSync(TARGET, xml);
    console.log(`build-sitemap: wrote sitemap.xml (${PAGES.length} urls)`);
    return;
  }
  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : '';
  if (current === xml) {
    console.log('build-sitemap: sitemap.xml is up to date');
    return;
  }
  console.error('build-sitemap: sitemap.xml is STALE. Run `npm run build:sitemap` and commit it.');
  process.exit(1);
}

try {
  main();
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
