#!/usr/bin/env node
/*
  build-mobile.js — generates mobile.html from index.html + style.css.

  mobile.html is NOT hand-edited. It is the same page with style.css
  inlined (GitHub Pages serves it as one request), the desktop/mobile
  redirect flipped to the mobile side, and a small phone-chrome override
  appended.

  The two files drifted badly once before: mobile.html was left on an
  older, ABRAXAS-only version of the site and never received the roster
  or the vessel copy. Every edit to index.html or style.css must be
  followed by `npm run build:mobile`, and `--check` fails CI-style if the
  committed mobile.html is stale.

  Usage:
    node scripts/build-mobile.js          # write mobile.html
    node scripts/build-mobile.js --check  # exit 1 if mobile.html is stale
*/

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'index.html');
const STYLES = path.join(ROOT, 'style.css');
const TARGET = path.join(ROOT, 'mobile.html');

/* Phone-only chrome. The header has no desktop equivalent on the phone:
   the brand block goes, and the menu becomes a small floating pill pinned
   bottom-right that opens a translucent panel upward. The page and the
   rain stay visible through both. */
const MOBILE_CHROME = `  <style>
    /*
      Phone chrome — the only rules that exist solely on mobile.html.
      Generated by scripts/build-mobile.js; edit it there, not here.
    */
    .topbar,
    .topbar.scrolled {
      position: fixed;
      top: auto;
      left: auto;
      right: calc(0.9rem + env(safe-area-inset-right, 0px));
      bottom: calc(0.9rem + env(safe-area-inset-bottom, 0px));
      width: auto;
      background: transparent;
      border: 0;
      box-shadow: none;
      backdrop-filter: none;
      -webkit-backdrop-filter: none;
    }
    .brand { display: none; }
    .topbar-inner {
      display: block;
      padding: 0;
      width: auto;
    }
    .nav-wrap {
      position: relative;
      width: auto;
      display: flex;
      justify-content: flex-end;
    }
    .menu-toggle {
      width: auto;
      min-height: 44px;
      padding: 0 1rem;
      gap: 0.5rem;
      background: rgba(10, 10, 10, 0.55);
      backdrop-filter: blur(14px);
      -webkit-backdrop-filter: blur(14px);
      border-color: rgba(255, 255, 255, 0.55);
      box-shadow: 0 0 14px rgba(255, 255, 255, 0.28), 0 0 34px rgba(255, 255, 255, 0.1);
      text-shadow: 0 0 8px rgba(255, 255, 255, 0.5);
    }
    .menu-toggle[aria-expanded="true"] {
      border-color: rgba(255, 255, 255, 0.85);
      box-shadow: 0 0 20px rgba(255, 255, 255, 0.45), 0 0 48px rgba(255, 255, 255, 0.18);
    }
    .menu-toggle span:last-child { font-size: 0.78rem; }
    .nav.open {
      position: absolute;
      right: 0;
      bottom: calc(100% + 0.6rem);
      min-width: 12.5rem;
      padding: 0.45rem;
      overflow: hidden;
      background: rgba(10, 10, 10, 0.32);
      backdrop-filter: blur(5px);
      -webkit-backdrop-filter: blur(5px);
      border: 1px solid rgba(255, 255, 255, 0.45);
      border-radius: var(--radius-sm);
      box-shadow: 0 0 18px rgba(255, 255, 255, 0.22), 0 0 44px rgba(255, 255, 255, 0.08);
    }
    /* script.js mirrors #matrix-rain into this canvas while the menu is
       open, so the rain falls inside the panel above the blur. */
    .nav-rain {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      pointer-events: none;
      opacity: 0.75;
    }
    .nav.open .nav-list { position: relative; }
    .nav-list { gap: 0.15rem; }
    .nav-list a {
      min-height: 40px;
      padding-block: 0.5rem;
      color: var(--text);
      text-shadow: 0 0 6px rgba(255, 255, 255, 0.35);
    }
    .nav-list a.active {
      background: rgba(255, 255, 255, 0.12);
      text-shadow: 0 0 10px rgba(255, 255, 255, 0.7);
    }
  </style>
`;

/* Each edit is (description, find, replace). A find that does not match
   exactly once aborts the build rather than silently emitting a
   half-converted page — that silence is how the last drift shipped. */
function edits(css) {
  return [
    [
      'inline style.css',
      '  <link rel="stylesheet" href="style.css" />\n',
      '  <style>\n' + css + '  </style>\n',
    ],
    [
      'flip the redirect to the mobile side',
      'data-page="desktop"',
      'data-page="mobile"',
    ],
    [
      'point the view toggle back at the desktop page',
      '<a class="inline-link view-toggle" href="mobile.html?mobile=1">Mobile site</a>',
      '<a class="inline-link view-toggle" href="index.html?desktop=1">Desktop site</a>',
    ],
    [
      // index.html advertises mobile.html as its phone alternate; the phone
      // page keeps only the canonical link back to index.html (the search
      // engines' separate-URL pattern), so the alternate must not survive.
      'drop the desktop-only alternate link',
      '  <link rel="alternate" media="only screen and (max-width: 820px)" href="https://www.htg.productions/mobile.html" />\n',
      '',
    ],
    ['append the phone chrome', '</head>\n', MOBILE_CHROME + '</head>\n'],
  ];
}

function build() {
  const source = fs.readFileSync(SOURCE, 'utf8');
  const css = fs.readFileSync(STYLES, 'utf8');

  let html = source;
  for (const [what, find, replace] of edits(css)) {
    const hits = html.split(find).length - 1;
    if (hits !== 1) {
      throw new Error(
        `build-mobile: cannot ${what} — expected 1 match in index.html, found ${hits}.\n` +
          `  looked for: ${find.trim().slice(0, 90)}\n` +
          '  index.html changed shape; update scripts/build-mobile.js to match.'
      );
    }
    html = html.replace(find, () => replace);
  }

  return (
    '<!-- GENERATED FILE — do not edit. Built from index.html + style.css by\n' +
    '     scripts/build-mobile.js. Run `npm run build:mobile` after changing\n' +
    '     either source, or this page falls behind the desktop one. -->\n' +
    html
  );
}

function main() {
  const html = build();
  const check = process.argv.includes('--check');

  if (!check) {
    fs.writeFileSync(TARGET, html);
    console.log(`build-mobile: wrote mobile.html (${html.length} bytes)`);
    return;
  }

  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : '';
  if (current === html) {
    console.log('build-mobile: mobile.html is up to date');
    return;
  }
  console.error(
    'build-mobile: mobile.html is STALE — it does not match index.html + style.css.\n' +
      'Run `npm run build:mobile` and commit the result.'
  );
  process.exit(1);
}

try {
  main();
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
